# 1. Introduction to NumPy and Array Creation (10 Marks)

Create a 1D NumPy array with the elements [10, 20, 30, 40, 50]. (2 Marks)

In [7]:
import numpy as np

In [9]:
a = np.array([10,20,30,40,50])

Create a 2D array of shape (2, 3) using numpy.zeros. (3 Marks)

In [32]:
b = np.zeros(6)
b = np.resize(b,(2,3))

Use numpy.linspace to create an array of 5 evenly spaced numbers between 0 and 100. (5 Marks)

In [37]:
c = np.linspace(0,100,5)

# 2. Array Indexing and Slicing (10 Marks) 
Using the 1D array [5, 10, 15, 20, 25, 30]:

Extract the first 3 elements. (2 Marks)

In [50]:
d = np.array([5,10,15,20,25,30])
print(d[:3])

[ 5 10 15]


Extract every second element. (3 Marks)

In [57]:
print(d[1::2])

[10 20 30]


Change the 4th element to 50 and print the updated array. (5 Marks)

In [62]:
d[3] = 50
print(d)

[ 5 10 15 50 25 30]


# 3. Reshaping Arrays (10 Marks)

Create a 1D array with 12 elements ranging from 1 to 12 using numpy.arange. (5 Marks)

In [72]:
e = np.arange(1,13)

Reshape it into a 2D array of shape (3, 4). (5 Marks)

In [81]:
e = np.resize(e,(3,4))

# 4. Broadcasting and Element-wise Operations (10 Marks)

Create a 1D array with elements [1, 2, 3, 4, 5].

Perform the following operations:
Add 10 to each element. (2 Marks)

In [102]:
f = np.arange(1,6)

In [114]:
add = f + 10

Multiply each element by 3. (3 Marks)

In [112]:
mult = f * 3

Calculate the square of each element. (5 Marks)

In [127]:
square = np.square(f)

# 5. Basic Statistics with Arrays (10 Marks)

Create a NumPy array representing daily temperatures for a week: [30, 32, 31, 29, 28, 33, 34].

In [131]:
t = np.array([30, 32, 31, 29, 28, 33, 34])

Find the mean temperature of the week. (3 Marks)

In [141]:
t_mean = np.mean(t)
print(t_mean)

31.0


Find the minimum and maximum temperatures. (3 Marks)

In [149]:
t_min = np.min(t)
t_max = np.max(t)
print("Minimum: " , t_min)
print("Maximum: " , t_max)

Minimum:  28
Maximum:  34


Calculate the total sum of the temperatures. (4 Marks)

In [156]:
t_sum = np.sum(t)
print(t_sum)

217


# 6. Real-World Problem: Sales Analysis (10 Marks)

Create a 2D array representing sales data for 2 products over 5 days:

Product 1: [200, 220, 250, 270, 300]

Product 2: [150, 160, 170, 180, 200]

In [171]:
product = np.array([[200, 220, 250, 270, 300] , [150, 160, 170, 180, 200]])
print(product)

[[200 220 250 270 300]
 [150 160 170 180 200]]


Calculate the total sales for each product. (4 Marks)

In [176]:
sale_p1 = sum(product[0])
sale_p2 = sum(product[1])
print("Total sale for first product: ",sale_p1)
print("Total sale for second product: ",sale_p2)

Total sale for first product:  1240
Total sale for second product:  860


Calculate the average sales per day. (3 Marks)

In [202]:
average_sales = np.mean(product, axis=0)
print("Average sales per day:", average_sales)

Average sales per day: [175. 190. 210. 225. 250.]


Find the day with the highest sales for each product. (3 Marks)

In [200]:
day = np.argmax(product, axis=1)
print("Highest sales day for first and second product:", day + 1)

Highest sales day for first and second product: [5 5]
